Controllers/MobilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Moboguide.Models;

namespace Moboguide.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MobilesController : Controller
    {
        Pcontext context = new Pcontext();
        private readonly IWebHostEnvironment env;
        public MobilesController(IWebHostEnvironment environment)
        {
            env = environment;
        }
        //AddMobile
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Mobile mobile, IFormFile img_file)
        {
            string path = Path.Combine(env.WebRootPath, "images"); // wwwroot/imgages/
            if (img_file != null)
            {
                if (img_file.FileName.EndsWith(".jpg") || img_file.FileName.EndsWith(".png"))
                {
                    path = Path.Combine(path, img_file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        img_file.CopyTo(stream);
                        mobile.ImagePath = img_file.FileName;
                    }
                }
                else
                {
                    ViewBag.imgNote = "This file not an image!";
                    return View("Create", mobile);
                }
            }
            else
            {
                mobile.ImagePath = "ph.jpg";
            }

            if (context.mobiles.Where(a => a.MobileName == mobile.MobileName).FirstOrDefault() != null)
            {
                ViewBag.Note = "This mobile already exist!";
                return View("Create", mobile);
            }
            if (mobile.MobileName == null)
            {
                return View("Create", mobile);
            }
            context.Add(mobile);
            context.SaveChanges();
            return RedirectToAction("allMobs", "Search");

        }
        //EditMobile
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mobile = context.mobiles.Find(id);
            if (mobile == null)
            {
                return NotFound();
            }
            return View(mobile);
        }
        [HttpPost]
        public IActionResult Edit(string id, Mobile mobile, IFormFile img_file)
        {
            if (id != mobile.MobileName)
            {
                return NotFound();
            }
            string imgpath = context.mobiles.Where(o => o.MobileName == id).Select(o => o.ImagePath).FirstOrDefault();
            if(imgpath != null)
                mobile.ImagePath = imgpath;
            try
            {

                string path = Path.Combine(env.WebRootPath, "images"); // wwwroot/images/
                if (img_file != null)
                {
                    if (img_file.FileName.EndsWith(".jpg") || img_file.FileName.EndsWith(".png"))
                    {
                        //delete old img
                        string oldpath = Path.Combine(path, imgpath);
                        path = Path.Combine(path, img_file.FileName);
                        if (oldpath != path)
                        {
                            if (System.IO.File.Exists(oldpath))
                            {
                                System.IO.File.Delete(oldpath);
                            }
                            //save new img
                            using (var stream = new FileStream(path, FileMode.Create))
                            {
                                img_file.CopyTo(stream);
                                mobile.ImagePath = img_file.FileName;
                            }
                        }

                    }
                    else
                    {
                        ViewBag.imgNote = "This file not an image!";
                        return View("Edit", mobile);
                    }
                }
                context.Update(mobile);
                context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MobileExists(mobile.MobileName))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("allMobs", "Search");
        }
        //DeleteMobile
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mobile = context.mobiles
                .FirstOrDefault(m => m.MobileName == id);
            if (mobile == null)
            {
                return NotFound();
            }

            return View(mobile);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(string id)
        {
            var mobile = context.mobiles.Find(id);
            if (mobile != null)
            {
                context.mobiles.Remove(mobile);
            }

            context.SaveChanges();
            return RedirectToAction("allMobs", "Search");
        }
        private bool MobileExists(string id)
        {
            return context.mobiles.Any(e => e.MobileName == id);
        }
    }
}

Controllers/SearchController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Moboguide.Models;
namespace Moboguide.Controllers
{
	public class SearchController : Controller
	{
		Pcontext  context = new Pcontext();
        ViewModel v = new ViewModel();
        [AllowAnonymous]
        public IActionResult srch(Mobile mob)
        {
            if (mob.MobileName == null)
            {
                ViewBag.searchNote = "Please Enter The Phone You Want To Search.";
                return View("../Home/Index");
            }
            List<Mobile> mobs = context.mobiles.ToList();
            List<Mobile> mobsreq = new List<Mobile>();
            foreach (var item in mobs)
            {
                if (item.MobileName.ToLower().Contains(mob.MobileName.ToLower()))
                {
                    mobsreq.Add(item);
                }
            }
            if (mobsreq.IsNullOrEmpty())
            {
                ViewBag.searchNote = "No Results Found!";
                return View("../Home/Index");
            }
            return View("allMobs", mobsreq);
        }
        [AllowAnonymous]
        public IActionResult allMobs()
        {
            List<Mobile> mobs = context.mobiles.ToList();
            return View(mobs);
        }
        [AllowAnonymous]
        public IActionResult details(string name)
        {
            if (name == null)
            {
                return NotFound();
            }
            var mob = context.mobiles.FirstOrDefault(x => x.MobileName == name);
            var cmnt = context.comments.Where(a => a.MobileName == name);
            List<KeyValuePair<string, Comment>> names = new();
            foreach (var c in cmnt)
            {  
                string? userName = context.users.Where(a => a.UserId == c.UserId).Select(a => a.UserName).FirstOrDefault();
                names.Add(new KeyValuePair<string, Comment>(userName, c));
            }
            ViewBag.cmmnts = names;
            v.mobile = mob;
            string cookieval = Request.Cookies["Username"];
            if (cookieval == null)
            {
                return View("srch", v);
            }
            int userid = context.users.FirstOrDefault(e => e.UserName == cookieval).UserId;
            var fav0 = context.mobilesUsers.FirstOrDefault(e => e.UserId == userid && e.MobileName == name);
            v.mobile_user = fav0;
            return View("srch", v);
        }
        [AllowAnonymous]
        public IActionResult compare(string name1, string? name2 = null)
        {
            if (name2 != null)
            {
                Mobile mob1 = context.mobiles.FirstOrDefault(x => x.MobileName == name1);
                Mobile mob2 = context.mobiles.FirstOrDefault(x => x.MobileName == name2);
                ViewBag.mob1 = mob1;
                ViewBag.mob2 = mob2;
                return View();
            }
            else
            {
                List<Mobile> mobs = context.mobiles.ToList();
                ViewBag.name1 = name1;
                return View("allMobs", mobs);
            }
        }
        public IActionResult favo(ViewModel fav)
        {
            string cookieval = Request.Cookies["UserName"];
            var mob = context.mobiles.FirstOrDefault(e => e.MobileName == fav.mobile.MobileName);
			v.mobile = mob;
			if (cookieval == null)
            {
                ViewBag.err = "Please sign in first";
                return View("srch", v);
            }
            var cmnt = context.comments.Where(a => a.MobileName == fav.mobile.MobileName);
            List<KeyValuePair<string, Comment>> names = new List<KeyValuePair<string, Comment>>();
            foreach (var c in cmnt)
            {
                string userName = context.users.Where(a => a.UserId == c.UserId).Select(a => a.UserName).FirstOrDefault();
                names.Add(new KeyValuePair<string, Comment>(userName, c));
            }
            ViewBag.cmmnts = names;
            int userid = context.users.FirstOrDefault(e => e.UserName == cookieval).UserId;
            MobileUser fav0 = context.mobilesUsers.FirstOrDefault(e => (e.UserId == userid && e.MobileName == fav.mobile.MobileName));
            if (fav0 == null)
            {
                fav0 = new MobileUser();
                fav0.UserId = userid;
                fav0.Rate = fav.mobile_user.Rate;
                fav0.MobileName = fav.mobile.MobileName;
                fav0.IsFavorite = fav.mobile_user.IsFavorite;
                context.mobilesUsers.Add(fav0);
                context.SaveChanges();
                v.mobile_user = fav0;
            }
            else
            {
                fav0.IsFavorite = fav.mobile_user.IsFavorite;
                fav0.Rate = fav.mobile_user.Rate;
                context.Update(fav0);
                context.SaveChanges();
            }
			var rates = context.mobilesUsers.Where(a => a.MobileName == fav.mobile.MobileName && a.Rate > 0).ToList();
			int count = 0; float totalrates = 0;
			foreach (var rate in rates)
			{
				count++;
				totalrates += rate.Rate;
			}
            if(count > 0)
			    mob.AvgRate = totalrates / count;
			context.SaveChanges();
            v.mobile = mob;
			v.mobile_user = fav0;
            return View("srch", v);
        }
        [Authorize(Policy = "AuthenticatedOnly")]
        public IActionResult favlist()
        {
            string? cookieval = Request.Cookies["UserName"];
            List<Mobile> favs = new List<Mobile>();

            if (cookieval == null)
            {
                ViewBag.errmsg = "Please sign in first ";
                return View("allmobs", favs);
            }
            int userid = context.users.Where(e => e.UserName == cookieval).Select(a=>a.UserId).SingleOrDefault();
            List<MobileUser> favlis = context.mobilesUsers.ToList();
            foreach (var fav in favlis)
            {
                if (fav.UserId == userid && fav.IsFavorite)
                {
                    var mob = context.mobiles.Where(e => e.MobileName == fav.MobileName).SingleOrDefault();
                    favs.Add(mob);
                }
            }
            return View("allmobs", favs);
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    var user = Context.Request.Cookies["UserName"];
    bool IsAdmin = User.IsInRole("Admin");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Moboguide.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-family:Cairo;color:rgb(3,7,175);font-weight:bold;">Moboguide</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="allMobs">All Mobiles</a>
                        </li>
                        @if(!string.IsNullOrEmpty(user))
                        {          
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Profile" asp-route-id=@user>@user</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogOut">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="favlist">Your Favorites</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignUp">SignUp</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogIn">Login</a>
                            </li>
                        }
                        @if (IsAdmin)
                        { 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AllUsers">All Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Mobiles" asp-action="Create">Insert New Mobile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AdminList">All Admins</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:white;">
        <div class="container">
            &copy; 2024 - Moboguide - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>